Mc 5244 resize root volume
cloud-ca/ui-driver-cloudca pull request #8
Opened 2017-05-25 18:32 UTC by franzpgarcia

2017-05-25 18:52 UTC, simongodard approved these changes
LGTM 👍 
Can you add a screenshot of what the form looks like after your UI changes?

2017-05-25 19:16 UTC, franzpgarcia commented
![screen shot 2017-05-25 at 3 15 45 pm](https://cloud.githubusercontent.com/assets/5419828/26466561/237deb78-415d-11e7-8b5b-d12fec3df096.png)
Here you go

2017-05-25 19:34 UTC, pdube commented
How are we managing the version dependency with CS?

2017-05-25 19:35 UTC, franzpgarcia commented
We only display it if the template supports it. The CS version is not important here.

2017-05-25 19:36 UTC, pdube commented
Ok got it

2017-05-25 19:36 UTC, pdube approved these changes

2017-05-25 20:53 UTC, prollynomial requested changes

2017-05-25 20:53 UTC, prollynomial commented on component/component.js
> +           return template.name.toLowerCase().indexOf('windows') == -1 && template.name.toLowerCase().indexOf('centos 6') == -1;
You could tighten this up with regexps

```js
return !template.name.match(/windows|centos 6/i);
```

2017-05-25 20:53 UTC, prollynomial commented on component/component.js
> +      var templateSizeInGb = selectedTemplate.size / 1024^3
I think you mean `Math.pow` - that's an xor.

2017-05-25 20:53 UTC, prollynomial commented on component/component.js
> +      selectedTemplate = selectedTemplate ? selectedTemplate : templateOptions[0]
Lines 203 and 204 can be condensed into

```js
var selectedTemplate = templateOptions.findBy('value', selectedTemplateId) || templateOptions[0];
```

2017-05-25 20:53 UTC, prollynomial commented on component/component.js
> +   updateResizableOnTemplateChange: function() {
Missing semicolons on every line in this function.

2017-05-25 20:53 UTC, prollynomial commented on component/component.js
> +      }
The loop here isn't necessary, this is pretty formulaic.

```js
var stepSize = selectedTemplate.stepSizeInGb,
    aligned = templateSizeInGb % stepSize === 0,
    minSizeInGb = stepSize * (Math.floor(templateSizeInGb / stepSize) + (aligned ? 0 : 1));
```

2017-05-25 20:57 UTC, franzpgarcia commented on component/component.js
> +      var templateSizeInGb = selectedTemplate.size / 1024^3
wow gg wp :P

2017-05-25 21:01 UTC, franzpgarcia commented on component/component.js
> +   updateResizableOnTemplateChange: function() {
Still not convinced :P but will do it for you guys.

2017-05-25 21:05 UTC, franzpgarcia commented on component/component.js
> +           return template.name.toLowerCase().indexOf('windows') == -1 && template.name.toLowerCase().indexOf('centos 6') == -1;
suboptimal but cleaner

2017-05-25 21:05 UTC, franzpgarcia commented on component/component.js
> +      }
I get what you're doing but it's not easier to understand lol.

2017-05-25 21:06 UTC, franzpgarcia commented on component/component.js
> +      selectedTemplate = selectedTemplate ? selectedTemplate : templateOptions[0]
will do

2017-05-25 21:06 UTC, prollynomial commented on component/component.js
> +           return template.name.toLowerCase().indexOf('windows') == -1 && template.name.toLowerCase().indexOf('centos 6') == -1;
You could pull out the regex to make it a constant outside the loop. It would make it less suboptimal ;)

2017-05-25 21:11 UTC, prollynomial commented on component/component.js
> +      }
I agree it's more dense, but it's not difficult to understand. If I wanted it to be difficult to understand I would've put `stepSize * (Math.floor(templateSizeInGb / stepSize) + !aligned)` :P

2017-05-26 15:30 UTC, franzpgarcia commented on component/component.js
> +           return template.name.toLowerCase().indexOf('windows') == -1 && template.name.toLowerCase().indexOf('centos 6') == -1;
Done

2017-05-26 18:22 UTC, merged